# -*- coding: utf-8 -*-
"""sentiment final code1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0MlUloobFhemN6js0qNviPu3xUZqhSR

sentiment
"""

import spacy
from spacy.lang.en import English
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.nn.functional import softmax
import os
import csv
import logging

# Load the model and tokenizer
model_name = "climatebert/distilroberta-base-climate-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Load SpaCy
nlp = spacy.load("en_core_web_sm")
nlp.max_length = 3500000  # Increase SpaCy's maximum text length

def read_file_with_fallback_encodings(file_path, encodings=('utf-8', 'ISO-8859-1')):
    """Attempt to read a file with multiple encodings."""
    for encoding in encodings:
        try:
            with open(file_path, 'r', encoding=encoding) as file:
                return file.read()
        except UnicodeDecodeError:
            continue
    raise UnicodeDecodeError(f"Failed to decode {file_path} with provided encodings: {encodings}")

def split_at_sentence_boundary(text, max_token_length):
    doc = nlp(text)
    current_chunk = []
    chunks = []
    current_length = 0
    special_tokens_length = tokenizer.num_special_tokens_to_add()

    for sent in doc.sents:
        sentence = sent.text.strip()
        sentence_tokens = tokenizer.tokenize(sentence, add_special_tokens=False)
        sentence_length = len(sentence_tokens)

        if current_length + sentence_length + special_tokens_length > max_token_length:
            chunks.append(' '.join(current_chunk))  # Convert list of tokens to string
            current_chunk = [sentence]
            current_length = sentence_length
        else:
            current_chunk.append(sentence)
            current_length += sentence_length

    if current_chunk:
        chunks.append(' '.join(current_chunk))
    return chunks

#  logging
logging.basicConfig(filename='../Utilities_2022_truncation_log.txt', level=logging.INFO,
                    format='%(asctime)s:%(levelname)s:%(message)s')

def sentiment_analysis(text):
    inputs = tokenizer(text, return_tensors="pt", padding="max_length", truncation=True, max_length=512)
    outputs = model(**inputs)
    probabilities = softmax(outputs.logits, dim=1)
    return probabilities[:, 0].item(), probabilities[:, 1].item(), probabilities[:, 2].item()

def process_files_in_folder(folder_path, output_folder_path):
    overall_scores = []
    file_scores = []

    for file_name in os.listdir(folder_path):
        if file_name.endswith('.txt'):
            file_path = os.path.join(folder_path, file_name)
            content = read_file_with_fallback_encodings(file_path)

            chunks = split_at_sentence_boundary(content, 512 - tokenizer.num_special_tokens_to_add())
            sentiment_scores = [sentiment_analysis(chunk) for chunk in chunks]

            file_average_scores = [sum(scores) / len(scores) for scores in zip(*sentiment_scores)]
            file_scores.append((file_name, *file_average_scores))
            overall_scores.extend(sentiment_scores)


    overall_average_scores = [sum(scores) / len(scores) for scores in zip(*overall_scores)]

    with open(os.path.join(output_folder_path, 'Utilities_2022(2)_24_file_sentiment_scores.csv'), 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['File Name', 'Opportunity', 'Neutral', 'Risk'])
        writer.writerows(file_scores)

    with open(os.path.join(output_folder_path, 'Utilities_overall_sentiment_scores.csv'), 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Opportunity', 'Neutral', 'Risk'])
        writer.writerow(overall_average_scores)

if __name__ == "__main__":
    print("Model and tokenizer loaded successfully.")
    # Update these paths as per your directory structure
    folder_path = ''
    output_folder_path = ''
    if not os.path.exists(output_folder_path):
        os.makedirs(output_folder_path)
    process_files_in_folder(folder_path, output_folder_path)

"""


```
`# This is formatted as code`
```

"""

