# -*- coding: utf-8 -*-
"""Topics final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjZPa5bVSygx3bfyz5eSUPyZzvlY7WSP
"""

import os
import torch
import pandas as pd
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from torch.nn.functional import softmax
import numpy as np
import spacy
import logging

def setup_logging(year):
    log_filename = f'InfoTech_{year}.log'
    logging.basicConfig(filename=log_filename, level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.INFO)
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    console_handler.setFormatter(formatter)
    logging.getLogger().addHandler(console_handler)
    logging.info(f"Logging setup complete for year {year}")

nlp = spacy.load("en_core_web_sm")
nlp.max_length = 3500000

def load_model():
    model_name = "nbroad/ESG-BERT"
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model, tokenizer

def read_file_with_fallback_encodings(file_path, encodings=('utf-8', 'ISO-8859-1')):
    for encoding in encodings:
        try:
            with open(file_path, 'r', encoding=encoding) as file:
                return file.read()
        except UnicodeDecodeError:
            continue
    raise UnicodeDecodeError(f"Failed to decode {file_path} with provided encodings: {encodings}")

def split_at_sentence_boundary(text, max_token_length, tokenizer):
    doc = nlp(text)
    chunks = []
    current_chunk = []
    current_tokens = []

    for sent in doc.sents:
        sentence = sent.text.strip()
        sentence_tokens = tokenizer.tokenize(sentence)

        if len(current_tokens) + len(sentence_tokens) > max_token_length:
            if current_chunk:
                chunks.append(" ".join(current_chunk))
            current_chunk = [sentence]
            current_tokens = sentence_tokens
        else:
            current_chunk.append(sentence)
            current_tokens.extend(sentence_tokens)

    if current_chunk:
        chunks.append(" ".join(current_chunk))

    return chunks

def analyze_text_chunks(model, tokenizer, text):
    max_length = 512
    stride = 128
    model.eval()
    device = next(model.parameters()).device
    model.to(device)

    tokens = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=max_length,
                       return_overflowing_tokens=True, stride=stride)
    predictions = []

    for i in range(len(tokens['input_ids'])):
        input_ids = tokens['input_ids'][i].unsqueeze(0).to(device)
        attention_mask = tokens['attention_mask'][i].unsqueeze(0).to(device)

        with torch.no_grad():
            outputs = model(input_ids, attention_mask=attention_mask)
            probabilities = softmax(outputs.logits, dim=1)
            predictions.append(probabilities)

    if predictions:
        avg_predictions = torch.mean(torch.stack(predictions), dim=0)
    else:
        avg_predictions = np.array([])
    return avg_predictions.squeeze().cpu().numpy()

def process_file(file_path, model, tokenizer):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()
        file_predictions = analyze_text_chunks(model, tokenizer, text)
        return file_predictions
    except Exception as e:
        logging.error(f"Error processing {file_path}: {str(e)}")
        return None

def process_folder(folder_path, model, tokenizer):
    results = {}
    for filename in os.listdir(folder_path):
        if filename.endswith('.txt'):
            file_path = os.path.join(folder_path, filename)
            file_predictions = process_file(file_path, model, tokenizer)
            if file_predictions is not None:
                results[filename] = file_predictions
    return results

def aggregate_scores(results):
    if not results:
        return np.array([])

    all_scores = np.concatenate([np.expand_dims(scores, axis=0) for scores in results.values()], axis=0)
    return np.mean(all_scores, axis=0)

def save_to_csv(results, aggregated_scores, output_file, index_to_name):
    data = {'Filename': list(results.keys()) + ['Aggregate']}
    for idx, label in index_to_name.items():
        data[label] = [results[filename][idx] if filename in results else 0 for filename in list(results.keys())] + [aggregated_scores[idx]]
    df = pd.DataFrame(data)
    df.to_csv(output_file, index=False)

def main():
    base_folder_path = ''
    model, tokenizer = load_model()

    index_to_name = {
        0: "Business_Ethics",
        1: "Data_Security",
        2: "Access_And_Affordability",
        3: "Business_Model_Resilience",
        4: "Competitive_Behavior",
        5: "Critical_Incident_Risk_Management",
        6: "Customer_Welfare",
        7: "Director_Removal",
        8: "Employee_Engagement_Inclusion_And_Diversity",
        9: "Employee_Health_And_Safety",
        10: "Human_Rights_And_Community_Relations",
        11: "Labor_Practices",
        12: "Management_Of_Legal_And_Regulatory_Framework",
        13: "Physical_Impacts_Of_Climate_Change",
        14: "Product_Quality_And_Safety",
        15: "Product_Design_And_Lifecycle_Management",
        16: "Selling_Practices_And_Product_Labeling",
        17: "Supply_Chain_Management",
        18: "Systemic_Risk_Management",
        19: "Waste_And_Hazardous_Materials_Management",
        20: "Water_And_Wastewater_Management",
        21: "Air_Quality",
        22: "Customer_Privacy",
        23: "Ecological_Impacts",
        24: "Energy_Management",
        25: "GHG_Emissions"
    }

    for year in range(2011, 2023):
        setup_logging(year)
        folder_path = f'{base_folder_path}/{year}'
        output_file = f'__{year}_TOPICS.csv'
        results = process_folder(folder_path, model, tokenizer)
        aggregated_scores = aggregate_scores(results)
        save_to_csv(results, aggregated_scores, output_file, index_to_name)
        print(f"Results for {year} saved to {output_file}")


if __name__ == "__main__":
    main()